### ISSUE TITLE
Release actions enforce artifacts names

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#135]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In the hidden action ```` we can see:

```yml
    - name: "Download the library artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts
```
The name of the artifacts can't be specified.

If we want to wider the pyansys actions user base, we need to be more flexible. 

### 📝 Steps to reproduce

Allow optional downloading actions

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
NA
```
