### ISSUE TITLE
Decouple main actions logic

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#166]
### 📝 Description of the feature

This is a complain I have already rised, but I need to insist.

The current actions are veeery specific and complex. For example, [doc-deploy-dev](https://github.com/pyansys/actions/blob/main/doc-deploy-dev/action.yml).

In this action we perform:
* Checkout (now it is optional)
* Download artifacts (and decompress)
* documentation logic (upload jekill files, generate redirection, etc)

I think these underlying actions should be grouped in "private" actions. For instance:

```yml
name: "Documentation deploy development version."
description: "Deploy development documentation to GitHub pages."

inputs:
  doc-artifact-name:
    description: "Name of the HTML documentation artifact."
    required: false
    default: 'documentation-html'
    type: string
  decompress_artifact:
    description: "If ``True``, the documentation artifact name is decompressed. If ``False``, content is assumed to be a collection of HTML files."
    required: false
    default: false
    type: string
[...]

runs:
  using: "composite"
  steps:

    - name: "Checkout"
       id: checkout
      uses: pyansys/actions/_doc_deploy_dev_checkout

    - name: "Download needed files"
      uses: pyansys/actions/_doc_deploy_dev_download

    - name: "Documentation generation"
      uses: pyansys/actions/_doc_deploy_dev_doc_gen
      with:
          artifact_path: id.output.artifact_path

    - name: "Deploy"
      uses: pyansys/actions/_doc_deploy_dev_deploy
```

### 💡 Steps for implementing the feature

I am happy to help (when I go back from holidays) if approved the PoC.
