### ISSUE TITLE
Adding zip compression mechanism to docs uploaded

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#54]
https://github.com/pyansys/actions/blob/53695e9807be5ce1692ff975c93dbb9b4285c36d/release-github/action.yml#L20-L25

At this point, what you are doing is basically downloading the HTML folder artifact for the docs. You have inside a bunch of folders and html files. What you want to do then when calling ``softprops/action-gh-release@v1`` is to "zip" it all together. I recommend adding a sub step like this one:

```yml
      - name: Zip HTML Documentation
        uses: vimtor/action-zip@v1
        with:
          files: html-documentation
          dest: html-documentation-compressed.zip
```
