### ISSUE TITLE
Consider adding caching mechanism for actions/setup-python

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#56]
Action ``actions/setup-python@v4`` allows to implement an automated caching mechanism as follows:

```yml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
```

We should consider exposing our dependencies location (as well as the package manager, though this one is typically pip) so that the action can generate the hash adequately and cache the packages.
