### ISSUE TITLE
Fix conditionals in v1 examples

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#73]
🐞 **Problem**
Examples in the documentation for v1 show conditionals once the job has executed, see:

```yaml
doc-deploy-dev:
  name: "Deploy developers documentation"
  runs-on: ubuntu-latest
  needs: doc-build
  steps:
    - name: "Deploy the latest documentation"
      if: github.event_name == 'push'
      uses: pyansys/actions/doc-deploy-dev@main
      with:
          cname: "<library>.docs.pyansys.com"
          token: ${{ secrets.GITHUB_TOKEN }}
```

This shows the job with a green check while the step appears in green, as it has not been executed. This weird situation can be avoided by simply placing the conditional at the job level:

```yaml
doc-deploy-dev:
  name: "Deploy developers documentation"
  runs-on: ubuntu-latest
  if: github.event_name == 'push'
  needs: doc-build
  steps:
    - name: "Deploy the latest documentation"
      uses: pyansys/actions/doc-deploy-dev@main
      with:
          cname: "<library>.docs.pyansys.com"
          token: ${{ secrets.GITHUB_TOKEN }}
```
